platform :ios, '6.0'
pod 'JSONKit', '~> 1.4'
pod 'Reachability', '~> 3.1.1'
pod 'RegexKitLite', '~> 4.0'
pod 'AFNetworking', '~> 2.2.4'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh'
pod 'SDWebImage', '~> 3.6'
pod 'FMDB', '~> 2.3'
pod 'IAPHelper'